// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalFooter from "./components/footer/globalFooter";
import Header from "./components/header/header-page";
import { Toaster } from "sonner";
import CartProvider from "@/hooks/cart-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'SU_PAL E-commerce App',
    template: '%s | SU_PAL E-commerce App',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <CartProvider> {/* Wrappa children med CartProvider */}
      <Header />
          <Toaster />
          {children}
          <GlobalFooter />
        </CartProvider>
      </body>
    </html>
  );
}
